### ISSUE TITLE
Alexa Skill

### ISSUE THREAD

**Issue by jojo3632** [wpietri/sucks#31]
hi,

This looks great! Can you package it as an Alexa so that we can control the N79 through Alexa?

Jordan.

**Comment by EtienneMD** [comment]
I've created an Alexa skill for personal use that I've successfully tested on my Deebot Slim 2. I've implemented Clean, Edge, Stop and Charge intents. I could make a few changes to make it suitable for  publishing it if that's okay with @wpietri. Should work on the N79.

**Comment by EtienneMD** [comment]
https://github.com/EtienneMD/Alexa-Ecovacs
