### ISSUE TITLE
Installation doesn't work as expected

### ISSUE THREAD

**Issue by sossienl** [wpietri/sucks#49]
When using Terminal (running on MacOs 10.13.6), I try to use:
**pip install sucks**

Error I get is: 
Could not find a version that satisfies the requirement sucks (from versions: )
No matching distribution found for sucks

I do have Python3 installed correctly, but it seems it cannot find sucks

**Comment by wpietri** [comment]
The package is in the Python repository and has been installed by many people from there: https://pypi.org/project/sucks/

So my suspicion here is that you don't have Python installed correctly. I don't have a Mac, so I can't provide detailed support, but I'd suggest you search on the error message and find solutions. This, for example, looks promising: https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies/49748494

In the future, please don't open tickets unless you're pretty sure your problem has something to do with the actual code in the repository. There are plenty of places to get general support, and many projects, this one included, have a mailing list for general questions.
