### ISSUE TITLE
Setting the water level in clean command

### ISSUE THREAD

**Issue by Nama** [wpietri/sucks#64]
Hi,

I'm looking for a way to set the water level (1, 2 or 3). I couldn't find any info how to do so.

**Comment by bmartin5692** [comment]
What model do you have? 

This is a guess, but the following might work:
`vacbot.run(VacBotCommand("SetWaterPermeability", {"v": "1"}))`

**Comment by Nama** [comment]
DEEBOT OZMO 610

I couldn't test this yet. `sucks clean 10` works, but I have trouble making `vacbot.run(Clean())` to work. Even tho, `vacbot.run(Charge())` works...

I'll try and will answer again, thank you!

**Comment by bmartin5692** [comment]
I think once #65 is addressed for you (see my comment there), this will resolve as well.  You should be able to run the set command either before or after a cleaning cycle starts without issue.

**Comment by Nama** [comment]
Yes, it works. 1 is lowest, 3 is highest level.
Care to put that info in https://github.com/bmartin5692/sucks/blob/master/protocol.md#cleaning ?

Thank you, very nice from you!

**Comment by niveksan** [comment]
Hi bmartin5692,

I'm looking for a way to specify the SpotArea adding an Option for the runtime. e.g. area 1 --15min
I tried the following with OZMO930: sucks area 1 clean 15 but it seems to result in two commands executed one after the other.
