### ISSUE TITLE
Is there a way to control multiple robots?

### ISSUE THREAD

**Issue by simeonhalsey** [wpietri/sucks#81]
Thanks for creating this, it's complete genius!
Is there a way to control multiple robots?  Or will I have to create 2 email accounts and attach a deebot to each.

Kind regards

**Comment by bmartin5692** [comment]
@simeonhalsey 
Check out https://github.com/wpietri/sucks/issues/60. It can be done, but you'll need to use the library instead of the CLI to do this.

**Comment by simeonhalsey** [comment]
Thank you Brian,

That’s perfect!

 Kind regards
