### ISSUE TITLE
Support for deebot 500?

### ISSUE THREAD

**Issue by C-Aniruddh** [wpietri/sucks#94]
The sucks fork from @bmartin5692 allows me to connect to my deebot 500 using the sucks API. However, the Move command fails with a `ReadTimeout` exception while making a request to the iotdevmanager. 

Is there any way to debug this? Or is it because of a server error on their side?

Link to fork: https://github.com/bmartin5692/sucks

Thanks,
Aniruddh

**Comment by wpietri** [comment]
I think the best place to discuss forks is probably on the fork. @bmartin5692, could you please turn on issues on your repo?
